"""empty message

Revision ID: 204a42e3d762
Revises: 9fb51d7af93c
Create Date: 2023-08-27 15:08:22.266950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204a42e3d762'
down_revision = '9fb51d7af93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stock_id')

    # ### end Alembic commands ###
