"""empty message

<<<<<<<< HEAD:migrations/versions/0f8b3ed545b2_.py
Revision ID: 0f8b3ed545b2
Revises: 
Create Date: 2023-09-01 21:29:19.245918
========
Revision ID: db2e30e66cdb
Revises: 
Create Date: 2023-09-01 16:16:25.525816
>>>>>>>> e28bbb9f807a6c1e12ab2a526bd42e13eea021d5:migrations/versions/db2e30e66cdb_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/0f8b3ed545b2_.py
revision = '0f8b3ed545b2'
========
revision = 'db2e30e66cdb'
>>>>>>>> e28bbb9f807a6c1e12ab2a526bd42e13eea021d5:migrations/versions/db2e30e66cdb_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('rol_company', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=800), nullable=False),
    sa.Column('salt', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_client', sa.String(length=250), nullable=False),
    sa.Column('email_client', sa.String(length=250), nullable=False),
    sa.Column('phone_client', sa.String(length=250), nullable=False),
    sa.Column('address_client', sa.String(length=250), nullable=False),
    sa.Column('rif_client', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_client')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_Stock', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('rif', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('buy_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('item', sa.String(length=250), nullable=False),
    sa.Column('price', sa.String(length=250), nullable=False),
    sa.Column('admission_date', sa.String(length=250), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('buy_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buy_order_id'], ['buy_order.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('buy_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buy_order_id'], ['buy_order.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('product')
    op.drop_table('buy_order')
    op.drop_table('stock')
    op.drop_table('client')
    op.drop_table('user')
    # ### end Alembic commands ###
