"""empty message

Revision ID: e348113a54a1
Revises: c92a3e99a002
Create Date: 2023-09-05 23:30:28.701726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e348113a54a1'
down_revision = 'c92a3e99a002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy_order', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
