"""empty message

<<<<<<<< HEAD:migrations/versions/c92a3e99a002_.py
Revision ID: c92a3e99a002
Revises: 
Create Date: 2023-09-05 23:27:23.009842
========
Revision ID: fda76a9f3729
Revises: 
Create Date: 2023-09-06 01:34:02.911416
>>>>>>>> 81ac80dd41ea5cdf98b6d593ce3e01c06afaeb52:migrations/versions/fda76a9f3729_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/c92a3e99a002_.py
revision = 'c92a3e99a002'
========
revision = 'fda76a9f3729'
>>>>>>>> 81ac80dd41ea5cdf98b6d593ce3e01c06afaeb52:migrations/versions/fda76a9f3729_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('rol_company', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=800), nullable=False),
    sa.Column('salt', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_client', sa.String(length=250), nullable=False),
    sa.Column('email_client', sa.String(length=250), nullable=False),
    sa.Column('phone_client', sa.String(length=250), nullable=False),
    sa.Column('address_client', sa.String(length=250), nullable=False),
    sa.Column('rif_client', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_client')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_Stock', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('rif', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('item', sa.String(length=250), nullable=False),
    sa.Column('price', sa.String(length=250), nullable=False),
    sa.Column('admission_date', sa.String(length=250), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buy_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy_order')
    op.drop_table('report')
    op.drop_table('product')
    op.drop_table('stock')
    op.drop_table('client')
    op.drop_table('user')
    # ### end Alembic commands ###
